/**
 * §4.9 corporate records: filled from database data, rendered to PDF, signed
 * by the owner, vaulted. These are the entity's own internal formalities —
 * never IRS/NYS forms (guardrail 4). Each carries a review note: the app is
 * not a lawyer or tax adviser.
 */
import { eq } from "drizzle-orm";
import type { Dbx } from "../db/client";
import { auditLog, compMethodologies, corporateRecords } from "../db/schema";
import { linkDocument, storeDocument } from "../vault/store";
import { htmlToPdf } from "./pdf";

export class RecordsError extends Error {}

const CSS = `
  body { font: 13px/1.55 Georgia, 'Times New Roman', serif; color: #111;
         max-width: 46rem; margin: 3rem auto; padding: 0 1.5rem; }
  h1 { font-size: 19px; text-transform: uppercase; letter-spacing: .04em; text-align: center; }
  h2 { font-size: 14px; margin-top: 1.6em; }
  .recitals p { margin: .5em 0; }
  .sig { margin-top: 4rem; }
  .sig .line { border-top: 1px solid #111; width: 20rem; margin-top: 3rem; padding-top: .3rem; }
  .note { font-size: 11px; color: #555; margin-top: 2.5rem; border-top: 1px solid #ccc; padding-top: .6rem; }
  ul { margin: .4em 0 .4em 1.2em; }
`;

function page(title: string, body: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>${CSS}</style></head><body>${body}
<p class="note">Generated by the S-Corp Back Office from database records. This document is an
internal corporate record template — review with counsel/CPA before relying on it. It is not an
official government form and nothing here is legal or tax advice.</p>
</body></html>`;
}

function esc(s: string): string {
  return s.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");
}

export type AccountablePlanPolicyInput = {
  entityName: string;
  memberName: string;
  adoptedOn: string; // YYYY-MM-DD
  effectiveFrom: string;
  substantiationWindowDays: number;
  reimbursementWindowDays: number;
  categories: string[];
};

export function renderAccountablePlanPolicy(i: AccountablePlanPolicyInput): string {
  const body = `
<h1>Accountable Plan for Employee Expense Reimbursement</h1>
<p><strong>${esc(i.entityName)}</strong> (the “Company”) adopts this accountable plan under
Treas. Reg. §1.62-2, effective ${i.effectiveFrom}, for the reimbursement of business expenses
paid by its employees, including its sole member-employee ${esc(i.memberName)}.</p>
<h2>1. Business connection</h2>
<p>The Company will reimburse only expenses with a business connection — expenses paid or
incurred in the performance of services as an employee of the Company, in the following
categories:</p>
<ul>${i.categories.map((c) => `<li>${esc(c)}</li>`).join("")}</ul>
<h2>2. Substantiation</h2>
<p>Each reimbursement request must be substantiated with documentary evidence (receipts,
statements, premium notices, or a written computation for home-office and business-use
percentages) within ${i.substantiationWindowDays} days after the expense is paid or incurred.
The Company will not reimburse unsubstantiated amounts.</p>
<h2>3. Return of excess</h2>
<p>Any advance or reimbursement in excess of substantiated expenses must be returned to the
Company within ${i.reimbursementWindowDays} days. Amounts not returned are treated as wages.</p>
<h2>4. Home office and mixed-use expenses</h2>
<p>Home-office reimbursements are computed from the business-use percentage of the residence
(square-footage method) applied to rent or eligible ownership costs, utilities, and insurance;
phone and internet are reimbursed at their stated business-use percentages. The computation
worksheet and inputs are retained with each reimbursement.</p>
<h2>5. Administration</h2>
<p>Reimbursements are processed through the Company's back-office system, which enforces this
plan's substantiation requirements; each approved submission and its supporting document are
retained for at least seven years.</p>
<div class="sig">
  <div class="line">${esc(i.memberName)}, Sole Member — adopted ${i.adoptedOn}</div>
</div>`;
  return page(`Accountable Plan — ${i.entityName}`, body);
}

export type PreYearConsentInput = {
  entityName: string;
  memberName: string;
  consentYear: number; // the coming tax year
  signedOn: string;
  compMethodologyVersion: number;
  compMethodologyDescription: string;
  compMethodologyFrozenAt: string | null;
  deferral401kElection: string; // e.g. "the annual employee elective deferral limit"
  accountablePlanAdoptedOn: string;
  deMinimisElection: boolean;
  ptetNote?: string;
};

export function renderPreYearConsent(i: PreYearConsentInput): string {
  const body = `
<h1>Written Consent of the Sole Member in Lieu of a Meeting</h1>
<p>The undersigned, being the sole member of <strong>${esc(i.entityName)}</strong> (the
“Company”), a New York limited liability company that has elected S-corporation treatment
effective January 1, 2027, hereby adopts the following resolutions for tax year
${i.consentYear}, effective before January 1, ${i.consentYear}:</p>
<div class="recitals">
<h2>Reasonable compensation methodology</h2>
<p><strong>RESOLVED</strong>, that officer compensation for ${i.consentYear} shall be determined
under the Company's reasonable-compensation methodology v${i.compMethodologyVersion}
(${esc(i.compMethodologyDescription)})${
    i.compMethodologyFrozenAt !== null
      ? `, frozen ${i.compMethodologyFrozenAt}`
      : " (to be frozen before January 1)"
  }, computed from contemporaneous time records and documented market rates.</p>
<h2>401(k) elective deferral</h2>
<p><strong>RESOLVED</strong>, that the member-employee's elective deferral election for
${i.consentYear} — ${esc(i.deferral401kElection)} — is on file with an effective date preceding
the pay date, to be withheld from the annual payroll.</p>
<h2>Accountable plan</h2>
<p><strong>RESOLVED</strong>, that the Company's accountable plan adopted
${i.accountablePlanAdoptedOn} remains in force for ${i.consentYear}, and reimbursements shall be
made only under its substantiation requirements.</p>
${
  i.deMinimisElection
    ? `<h2>De minimis safe-harbor election</h2>
<p><strong>RESOLVED</strong>, that the Company intends to apply the de minimis safe harbor of
Treas. Reg. §1.263(a)-1(f) for ${i.consentYear} and to attach the election statement to its
timely filed return.</p>`
    : ""
}
${i.ptetNote !== undefined ? `<h2>Pass-through entity tax</h2><p>${esc(i.ptetNote)}</p>` : ""}
</div>
<div class="sig">
  <div class="line">${esc(i.memberName)}, Sole Member — ${i.signedOn}</div>
</div>`;
  return page(`Pre-Year Consent ${i.consentYear} — ${i.entityName}`, body);
}

export type GeneratedRecord = {
  recordId: number;
  documentId: bigint;
  mime: "application/pdf" | "text/html";
};

export async function generateRecord(
  db: Dbx,
  args: {
    kind: "accountable_plan_policy" | "preyear_consent" | "annual_consent" | "de_minimis_election";
    taxYear: number | null;
    title: string;
    html: string;
    data: Record<string, unknown>;
  },
): Promise<GeneratedRecord> {
  const rendered = htmlToPdf(args.html);
  return await db.transaction(async (tx) => {
    const { document } = await storeDocument(tx, {
      filename:
        args.title.replaceAll(/[^A-Za-z0-9 _-]/g, "").replaceAll(" ", "-").toLowerCase() +
        (rendered.mime === "application/pdf" ? ".pdf" : ".html"),
      mime: rendered.mime,
      bytes: rendered.bytes,
      source: "generated",
      year: args.taxYear ?? undefined,
    });
    const [record] = await tx
      .insert(corporateRecords)
      .values({
        kind: args.kind,
        taxYear: args.taxYear,
        title: args.title,
        data: args.data,
        documentId: document.id,
      })
      .returning({ id: corporateRecords.id });
    await linkDocument(tx, document.id, "corporate_record", record!.id);
    await tx.insert(auditLog).values({
      actor: "owner",
      action: "generate_corporate_record",
      objectType: "corporate_record",
      objectId: String(record!.id),
      detail: { kind: args.kind, taxYear: args.taxYear, title: args.title },
    });
    return { recordId: record!.id, documentId: document.id, mime: rendered.mime };
  });
}

/** Convenience: pre-year consent straight from the live methodology row. */
export async function generatePreYearConsent(
  db: Dbx,
  args: {
    entityName: string;
    memberName: string;
    consentYear: number;
    signedOn: string;
    methodologyId: number;
    deferral401kElection: string;
    accountablePlanAdoptedOn: string;
    deMinimisElection: boolean;
    ptetNote?: string;
  },
): Promise<GeneratedRecord> {
  const [m] = await db
    .select()
    .from(compMethodologies)
    .where(eq(compMethodologies.id, args.methodologyId));
  if (!m) throw new RecordsError(`methodology ${args.methodologyId} not found`);
  const html = renderPreYearConsent({
    entityName: args.entityName,
    memberName: args.memberName,
    consentYear: args.consentYear,
    signedOn: args.signedOn,
    compMethodologyVersion: m.version,
    compMethodologyDescription: m.description,
    compMethodologyFrozenAt: m.frozenAt?.toISOString().slice(0, 10) ?? null,
    deferral401kElection: args.deferral401kElection,
    accountablePlanAdoptedOn: args.accountablePlanAdoptedOn,
    deMinimisElection: args.deMinimisElection,
    ptetNote: args.ptetNote,
  });
  return generateRecord(db, {
    kind: "preyear_consent",
    taxYear: args.consentYear,
    title: `Pre-year consent ${args.consentYear}`,
    html,
    data: { ...args, methodologyVersion: m.version, methodologyFrozenAt: m.frozenAt },
  });
}

const REQUIRED_STANDING = [
  ["cp261", "IRS S-election acceptance (CP261)"],
  ["ct6_approval", "NYS CT-6 approval"],
  ["ein_letter", "EIN assignment letter"],
  ["operating_agreement", "Operating agreement"],
  ["plan_adoption", "Solo 401(k) plan adoption agreement"],
  ["insurance_policy", "Insurance policy in force"],
  ["ny_employer_registration", "NY employer registration confirmation"],
] as const;

/** §4.9: track that each standing document exists; flag gaps. */
export async function standingDocumentGaps(
  db: Dbx,
): Promise<Array<{ standingKind: string; label: string }>> {
  const rows = await db
    .select()
    .from(corporateRecords)
    .where(eq(corporateRecords.kind, "standing"));
  const present = new Set(
    rows.filter((r) => r.documentId !== null).map((r) => r.standingKind ?? ""),
  );
  return REQUIRED_STANDING.filter(([kind]) => !present.has(kind)).map(([standingKind, label]) => ({
    standingKind,
    label,
  }));
}
